apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-api
  namespace: eddington-admin
spec:
  selector:
    matchLabels:
      app: eddington-api
  template:
    metadata:
      labels:
        app: eddington-api
    spec:
      serviceAccountName: eddington-admin
      containers: 
      - name: eddington-api
        image: nullchannel/eddington-api:latest
        command: ["app/api"]
        arg: ["-debug"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
