apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-container-builder
spec:
  selector:
    matchLabels:
      app: eddington-container-builder
  template:
    metadata:
      labels:
        app: eddington-container-builder
    volumes:
    - name: docker-socket
      hostPath:
        path: "/run/containerd/containerd.sock"
        type: File
    - name: docker-config
      hostPath:
        path: "/var/lib/containerd"
    spec:
      containers: 
      - name: eddington-container-builder
        image: nullchannel/eddington-container-builder:latest
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
        env:
          - name: REGISTRY_URL
            valueFrom:
              configMapKeyRef:
                name: container-builder-config
                key: REGISTRY_URL
          - name: DOCKER_HOST
            valueFrom:
              configMapKeyRef:
                name: container-builder-config 
                key: DOCKER_HOST
