# permissions for end users to view dontusemes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dontuseme-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: null-watcher-go
    app.kubernetes.io/part-of: null-watcher-go
    app.kubernetes.io/managed-by: kustomize
  name: dontuseme-viewer-role
rules:
- apiGroups:
  - deleteme.nullcloud.io
  resources:
  - dontusemes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deleteme.nullcloud.io
  resources:
  - dontusemes/status
  verbs:
  - get
