apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: main-builder
  namespace: eddington
spec:
  serviceAccountName: build-container-service-account
  tag: nullchannel/eddington-builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/go
