apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-container-service-account
  namespace: eddington
secrets:
- name: eddington-registry-credentials
imagePullSecrets:
- name: eddington-registry-credentials
